{"name": "Ошибка при неверных логине и пароле", "status": "passed", "start": 1730138235094, "stop": 1730138235355, "uuid": "5321c74f-f673-4aa1-bb70-d44a927434bf", "historyId": "a845ce24826f8b8746dc0f52d5788fa8", "testCaseId": "a845ce24826f8b8746dc0f52d5788fa8", "fullName": "tests.courier.test_login_courier.TestLoginCourier#test_courier_login_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests.courier"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "WIN-975IU3SH152"}, {"name": "thread", "value": "48456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.courier.test_login_courier"}]}